### ISSUE TITLE
Type 'DiffableTextStyle' has no member 'currency'

### ISSUE THREAD

**Issue by goenning** [oscbyspro/DiffableTextViews#170]
Hi, this package looks great, thanks for sharing it!

I'm new to Swift and I'm getting this error, not sure why. Any pointers?

![Screenshot 2023-05-17 at 10 50 24](https://github.com/oscbyspro/DiffableTextViews/assets/94755/a1dff0c0-26ea-4033-96ae-4028dbd62e96)

**Comment by oscbyspro** [comment]
Try adding "DiffableTextViews" to the "Link Binary With Libraries" section in "Build Phases" of your Xcode app target.

<img width="1150" alt="such-link-much-apple" src="https://github.com/oscbyspro/DiffableTextViews/assets/91259715/5ed67c52-a759-4bec-a541-2b8690877889">

**Comment by oscbyspro** [comment]
I'm closing this issue since a week has passed without comment.
