### ISSUE TITLE
Awaiting improved interoperability.

### ISSUE THREAD

**Issue by oscbyspro** [oscbyspro/DiffableTextViews#69]
## Public UIKit compatible environment values

Mimicking environment values adds a lot of overhead, for library authors and especially for users. Nobody wants 12 different modules with 12 different ways of writing the same value to the environment. In an alternative universe, where environment values are exposed, there is peace and harmony and all nations sing Kumbayah because custom 3rd party iOS libraries `just work` as if Apple themselves had built them.

### Use of SwiftUI.Font, environment \\.font

Requires public SwiftUI.Font to UIKit.UIFont conversion.

### Use of view.toolbar as input accessory view

Requires exposure of whatever is used behind the scenes.

### Use of other environment values

`Private` environment values == `decent` 3rd party libraries.
`Public` environment values == `amazing` 3rd party libraries.

**Comment by SwiftiOSStudio** [comment]
This project only needs SwiftUI.Font there is no need for UIKit.UIFont

**Comment by oscbyspro** [comment]
I agree, if you tell me how to set a UITextField’s font using SwiftUI.Font. As far as I know, it’s not yet possible. If/when it is possible, SwiftUI.Font is/would be enough. Currently, I use UIFont and a [SwiftUI-esque wrapper](https://github.com/oscbyspro/DiffableTextViews/blob/main/Sources/DiffableTextKitXUIKit/Models/Font.swift).

**Comment by oscbyspro** [comment]
It appears that SwiftUI’s toolbar and environment values are still private. SwiftUI.Font still cannot be converted to UIKit.UIFont, even after dub dub. My sadness is infinite and immeasurable...
